#!/bin/bash

PROJ="ach"
JOB_NAME="configure-buckets"

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

oc create cm -n ach bucket-script --from-file=${BASE}/bucket_notifications.py

cat <<EOF | oc apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: $JOB_NAME
  namespace: $PROJ
spec:
  completions: 1
  selector: {}
  template:
    metadata:
      name: $JOB_NAME
    spec:
      containers:
        - name: $JOB_NAME
          image: image-registry.openshift-image-registry.svc:5000/openshift/python:3.8-ubi8
          volumeMounts:
          - name: script
            mountPath: "/app"
          env:
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_ACCESS_KEY_ID
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-secret
                key: AWS_SECRET_ACCESS_KEY
          command:
          - /bin/bash
          args:
          - "-c"
          - |
            pip3 install boto3 botocore argparse
            
            python3 /app/bucket_notifications.py
      restartPolicy: Never
      volumes:
      - name: script
        configMap:
          name: bucket-script
EOF

echo -n "waiting for pod to appear..."
until POD="$(oc get -n $PROJ po -l job-name=$JOB_NAME -o name 2>/dev/null)"; do
  echo -n "."
  sleep 5
done
echo "done"

until oc logs -n $PROJ -f $POD; do
  sleep 5
done

echo -n "waiting for job to complete..."
while [ $(oc get -n $PROJ job/$JOB_NAME --no-headers 2>/dev/null | grep "1/1" | wc -l) -lt 1 ]; do
  echo -n "."
  sleep 10
done
echo "done"

oc delete -n $PROJ job/$JOB_NAME
oc delete -n $PROJ cm/bucket-script
