#!/bin/bash

set -e

echo "installing serverless operator..."
cat <<EOF | oc create -f -
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-serverless
spec:
  finalizers:
  - kubernetes
status: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: KnativeEventing.v1alpha1.operator.knative.dev,KnativeKafka.v1alpha1.operator.serverless.openshift.io,KnativeServing.v1alpha1.operator.knative.dev
  generateName: openshift-serverless-
  namespace: openshift-serverless
spec: {}
status: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/serverless-operator.openshift-serverless: ""
  name: serverless-operator
  namespace: openshift-serverless
spec:
  channel: stable
  installPlanApproval: Automatic
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: serverless-operator.v1.16.0
status: {}
EOF

echo -n "waiting for CSV to appear..."
while [ $(oc get csv --no-headers -n openshift-serverless 2>/dev/null | grep serverless | grep " Succeeded" | wc -l) -lt 1 ]; do
  echo -n "."
  sleep 10
done
echo "done"

echo "installing knative-serving..."
cat <<EOF | oc apply -f -
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
    name: knative-serving
    namespace: knative-serving
EOF

echo -n "waiting for knative-serving to be ready..."
while [ $(oc get -n knative-serving knativeserving.operator.knative.dev/knative-serving --no-headers 2>/dev/null | grep "True" | wc -l) -lt 1 ]; do
  echo -n "."
  sleep 10
done
echo "done"

echo -n "installing knative-eventing..."
cat <<EOF | oc apply -f -
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
    name: knative-eventing
    namespace: knative-eventing
EOF

echo -n "waiting for knative-eventing to be ready..."
while [ $(oc get knativeeventing.operator.knative.dev/knative-eventing -n knative-eventing --no-headers 2>/dev/null | grep "True" | wc -l) -lt 1 ]; do
  echo -n "."
  sleep 10
done
echo "done"
