#!/bin/bash

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

cat <<EOF | oc create -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: ach-
  namespace: ach
spec:
  targetNamespaces:
  - ach
status: {}
EOF

cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/grafana-operator.ach: ""
  name: grafana-operator
  namespace: ach
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v3.10.3
status: {}
EOF

echo -n "waiting for Grafana api resource..."
while [ $(oc api-resources | grep '^grafanas' | wc -l) -lt 1 ]; do
  echo -n "."
  sleep 10
done
echo "done"

cat <<EOF | oc apply -f -
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-grafana
  namespace: ach
spec:
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  ingress:
    enabled: true
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
EOF

echo -n "waiting for grafana route to appear..."
until oc get -n ach route/grafana-route &> /dev/null; do
  echo -n "."
  sleep 10
done
echo "done"

echo -n "waiting for GrafanaDataSource api resource..."
while [ $(oc api-resources | grep '^grafanadatasources' | wc -l) -lt 1 ]; do
  echo -n "."
  sleep 10
done
echo "done"

BASICAUTH=$(oc get secret/grafana-datasources -n openshift-monitoring -o json | jq -r '.data."prometheus.yaml"' | base64 -d | jq -r '.datasources[0].basicAuthPassword')
cat ${BASE}/../demos/ach/grafana-prometheus-datasource.yaml | sed -e "s|basicAuthPassword: .*|basicAuthPassword: \"$BASICAUTH\"|" | oc apply -f -

oc apply -f ${BASE}/../demos/ach/grafana-mysql-datasource.yaml
oc apply -f ${BASE}/../demos/ach/grafana-ach-dashboard.yaml

oc wait -n ach --for=condition=available deploy/grafana-deployment --timeout=300s

echo "Grafana URL: https://$(oc get -n ach route/grafana-route -o jsonpath='{.spec.host}')"
open https://$(oc get -n ach route/grafana-route -o jsonpath='{.spec.host}')
