#!/bin/bash

cat <<EOF | oc apply -f -
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: kafdrop
  namespace: ach
spec:
  selector:
    app: kafdrop
  replicas: 1
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
          - name: KAFKA_BROKERCONNECT
            value: "my-cluster-kafka-bootstrap:9092"
          - name: JVM_OPTS
            value: "-Xms32M -Xmx64M"
          - name: SERVER_SERVLET_CONTEXTPATH
            value: "/"
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: ach
spec:
  selector:
    app: kafdrop
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafdrop
  namespace: ach
spec:
  to:
    kind: Service
    name: kafdrop
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  port:
    targetPort: 9000
  wildcardPolicy: None
EOF

echo -n "waiting for pod to be ready..."
while [ $(oc get po -n ach -l deploymentconfig=kafdrop --no-headers 2>/dev/null | grep "1/1" | wc -l) -lt 1 ]; do
  echo -n "."
  sleep 10
done

sleep 10

open http://$(oc get -n ach route/kafdrop -o jsonpath='{.spec.host}')
