#!/bin/bash

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

oc apply -f ${BASE}/../demos/ach/service-odfi-split.yaml
oc apply -f ${BASE}/../demos/ach/service-rdfi-split.yaml
oc apply -f ${BASE}/../demos/ach/service-rdfi-process.yaml

echo -n "waiting for services to be ready..."
while [ $(oc get service.serving.knative.dev --no-headers -n ach 2>/dev/null | grep True | wc -l) -lt 3 ]; do
  echo -n "."
  sleep 10
done
echo "done"

oc apply -f ${BASE}/../demos/ach/kafkasource-odfi-split.yaml
oc apply -f ${BASE}/../demos/ach/kafkasource-rdfi-split.yaml
oc apply -f ${BASE}/../demos/ach/kafkasource-rdfi-process.yaml
