#!/bin/bash

PROJ="install"
JOB_NAME="install-demo"

cd `dirname $0`
BASE=`pwd`
cd - >> /dev/null

oc new-project $PROJ || oc project $PROJ

oc adm policy remove-cluster-role-from-user cluster-admin -z install -n $PROJ 2>/dev/null
oc delete -n $PROJ sa install 2>/dev/null

set -e

oc create -n $PROJ sa install
oc adm policy add-cluster-role-to-user cluster-admin -z install -n $PROJ

cat <<EOF | oc apply -n $PROJ -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: $JOB_NAME
spec:
  completions: 1
  selector: {}
  template:
    metadata:
      name: $JOB_NAME
    spec:
      serviceAccountName: install
      containers:
        - name: $JOB_NAME
          image: ghcr.io/kwkoo/ocp-install:4.7
          volumeMounts:
          - name: install
            mountPath: "/install"
          command:
          - /bin/bash
          args:
          - "-c"
          - |
            git clone https://github.com/kwkoo/datapipelines.git /install/git

            cd /install/git

            make deploy

      restartPolicy: Never
      volumes:
      - name: install
        emptyDir: {}
EOF

echo -n "waiting for pod to appear..."
until POD="$(oc get -n $PROJ po -l job-name=$JOB_NAME -o name 2>/dev/null)"; do
  echo -n "."
  sleep 5
done
echo "done"

until oc logs -n $PROJ -f $POD; do
  sleep 5
done

echo "installation completed, cleaning up..."

set +e

oc delete -n $PROJ job/$JOB_NAME
oc adm policy remove-cluster-role-from-user cluster-admin -z install -n $PROJ
oc delete -n $PROJ sa install
oc delete project $PROJ
oc project default
